FROM ubuntu:16.04

# set the environment variables
ENV cnvkit_version 0.9.6
ENV PYSAM_VERSION=0.7.7

# run update and install necessary tools
RUN apt-get update && apt-get install -y \
    build-essential \
    vim \
    gcc \
    vim \
    sudo \
    tar \
    nano \
    unzip \
    curl \
    libnss-sss \
    python3 \
    python3-pip \
    python3-numpy \
    python3-scipy \
    python3-matplotlib \
    python3-reportlab \
    python3-biopython \
    gfortran \
    libreadline-dev \
    libpcre3-dev \
    libcurl4-openssl-dev \
    libncurses5-dev \
    libncursesw5-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libssl-dev \
    libxml2-dev \
    python2.7 \
    python-pip \
    libx11-dev \
    libxpm-dev \
    libxft-dev \
    libxext-dev \
    git binutils \
    aptitude \
    gcc-multilib \ 
    libblas-dev \
    xorg-dev \
    libopenblas-dev \
    gobjc++ \
    openssl \
    cpanminus \
    fort77 \
    wget \
    git \
    automake \
    g++


RUN pip3 install pandas --upgrade
RUN pip3 install pyfaidx
RUN pip3 install future
RUN pip3 install pysam
RUN pip3 install pomegranate

RUN pip install Pysam==${PYSAM_VERSION}

ADD . /home

WORKDIR /home

RUN cd /home && wget https://cran.r-project.org/src/base/R-3/R-3.5.2.tar.gz && tar -zxvf R-3.5.2.tar.gz
RUN cd /home && rm -r R-3.5.2.tar.gz
RUN cd /home/R-3.5.2 && ./configure
RUN cd /home/R-3.5.2 && make
RUN cd /home/R-3.5.2 && make install

RUN R --vanilla -e 'install.packages(c("devtools", "BiocManager"), repos="http://cran.us.r-project.org")'
RUN R --vanilla -e 'BiocManager::install(c("DNAcopy", "R.utils", "ExomeDepth", "packrat", "nnls", "Hmisc", "mgcv", "plyr"))'


RUN cd /home && wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 && tar -xvjf htslib-1.9.tar.bz2
RUN cd /home && rm -r htslib-1.9.tar.bz2
RUN cd /home/htslib-1.9 && ./configure
RUN cd /home/htslib-1.9 && make
RUN cd /home/htslib-1.9 && make install


RUN cd /home && wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && tar -xvjf samtools-1.9.tar.bz2
RUN cd /home && rm -r samtools-1.9.tar.bz2
RUN cd /home/samtools-1.9 && ./configure
RUN cd /home/samtools-1.9 && make
RUN cd /home/samtools-1.9 && make install


RUN cd /home && wget https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools-2.28.0.tar.gz && tar -zxvf bedtools-2.28.0.tar.gz
RUN cd /home && rm -r bedtools-2.28.0.tar.gz  
RUN cd /home/bedtools2 && make
RUN cd /home/bedtools2 && make install


RUN cd /home && wget https://github.com/broadinstitute/gatk/releases/download/4.1.2.0/gatk-4.1.2.0.zip && unzip gatk-4.1.2.0.zip
RUN cd /home && rm -r gatk-4.1.2.0.zip
RUN cd /home/gatk-4.1.2.0 && ./gatk


RUN cd /home && wget http://sourceforge.net/projects/bio-bwa/files/bwa-0.7.12.tar.bz2 && tar -xvjf bwa-0.7.12.tar.bz2
RUN cd /home && rm -r bwa-0.7.12.tar.bz2
RUN cd /home/bwa-0.7.12 && make


RUN cd /home && wget http://biopython.org/DIST/biopython-1.74.tar.gz && tar -xzvf biopython-1.74.tar.gz
RUN cd /home/biopython-1.74 && python setup.py install
RUN cd /home && rm -r biopython-1.74.tar.gz


RUN cd /home && wget https://github.com/RahmanTeam/DECoN/archive/v1.0.2.tar.gz && tar -xzvf v1.0.2.tar.gz
RUN rm -r /home/v1.0.2.tar.gz

RUN curl -SL https://github.com/etal/cnvkit/archive/v${cnvkit_version}.tar.gz | tar -zxvC /home

RUN cd /home && wget http://sv.gersteinlab.org/phase1bkpts/breakseq2_bplib_20150129.zip && unzip breakseq2_bplib_20150129.zip
RUN cd /home && rm -r breakseq2_bplib_20150129.zip

RUN cd /home && wget https://github.com/bioinform/breakseq2/archive/2.2.tar.gz && tar -xzvf 2.2.tar.gz
RUN cd /home && rm -r 2.2.tar.gz


